# Generated by Django 4.1.2 on 2022-10-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppxl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mptp',
            options={'ordering': ['name'], 'verbose_name_plural': 'MPTP'},
        ),
    ]
