# Generated by Django 4.1.2 on 2022-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppxl', '0002_alter_mptp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mptp',
            name='mptp_applies',
            field=models.BooleanField(default=True),
        ),
    ]
